from odoo import api, fields, models, tools, _
from odoo.exceptions import UserError, ValidationError

class LazadaBrand(models.Model):
    _name = 'lazada.brand'
    _description = 'Lazada Brand'

    name = fields.Char('Name')
    name_en = fields.Char('Name EN')
    global_identifier = fields.Char('Global Identifier')
    lazada_brand_id = fields.Integer('Lazada Brand ID')
